# Generated by setup_srtod_datasets.py. Do not edit as a canonical baseline.
# Dataset: levir_ship
# Model variant: SR-TOD SRTOD_CascadeRCNN R50-FPN with DGFE/reconstruction module.
_base_ = ['/mnt/data/varroa/mmdetection/SR-TOD/srtod_project/srtod_cascade_rcnn/config/srtod-cascade-rcnn_r50_fpn_visdrone.py', '/mnt/data/varroa/mmdetection/SR-TOD/configs/_base_/default_runtime.py']

custom_imports = dict(
    imports=[
        'srtod_project.srtod_cascade_rcnn.srtod_cascadercnn',
        'srtod_project.srtod_cascade_rcnn.srtod_datapreprocessor',
        'srtod_project.srtod_cascade_rcnn.srtod_twostagedetector',
    ],
    allow_failed_imports=False,
)

dataset_type = 'CocoDataset'
classes = ('ship',)

# The upstream SR-TOD config defaults to 10 classes. This explicit one-class
# override is required for each of the local datasets.
model = dict(
    roi_head=dict(
        bbox_head=[
            dict(num_classes=1),
            dict(num_classes=1),
            dict(num_classes=1),
        ]
    ),
)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PackDetInputs'),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(1333, 800), keep_ratio=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='PackDetInputs', meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor')),
]


train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type=dataset_type,
        ann_file='/mnt/data/varroa/mmdetection/mmdetection/data/levir_ship_coco_recovered/annotations/train.json',
        data_prefix=dict(img='/mnt/data/varroa/mmdetection/LevirShipData/All Images/'),
        metainfo=dict(classes=classes),
        filter_cfg=dict(filter_empty_gt=True, min_size=1),
        pipeline=train_pipeline,
    ),
)
val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file='/mnt/data/varroa/mmdetection/mmdetection/data/levir_ship_coco_recovered/annotations/val.json',
        data_prefix=dict(img='/mnt/data/varroa/mmdetection/LevirShipData/All Images/'),
        metainfo=dict(classes=classes),
        test_mode=True,
        pipeline=test_pipeline,
    ),
)
test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file='/mnt/data/varroa/mmdetection/mmdetection/data/levir_ship_coco_recovered/annotations/test.json',
        data_prefix=dict(img='/mnt/data/varroa/mmdetection/LevirShipData/All Images/'),
        metainfo=dict(classes=classes),
        test_mode=True,
        pipeline=test_pipeline,
    ),
)
val_evaluator = dict(type='CocoMetric', ann_file='/mnt/data/varroa/mmdetection/mmdetection/data/levir_ship_coco_recovered/annotations/val.json', metric='bbox')
test_evaluator = dict(type='CocoMetric', ann_file='/mnt/data/varroa/mmdetection/mmdetection/data/levir_ship_coco_recovered/annotations/test.json', metric='bbox')

# Conservative setup defaults. Training seeds, epochs, AMP, and upload policy
# remain explicit Marimo-run parameters rather than hidden config assumptions.
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=12, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
work_dir = '/mnt/data/varroa/mmdetection/work_dirs/srtod_cascade/levir_ship'
